MOCK_METRICS = {
    "overview": {
        "followers": 6240,
        "follower_growth_pct": 14.2,
        "avg_views": 18400,
        "avg_likes": 1230,
        "avg_comments": 87,
        "avg_shares": 143,
        "engagement_rate": 7.8,
    },
    "posts": [
        {
            "title": "二手改造 – 8 块钱外套穿出高定感",
            "platform": "抖音",
            "views": 42000,
            "likes": 3100,
            "comments": 214,
            "shares": 480,
            "posted": "周一 19:00",
            "pillar": "二手改造",
        },
        {
            "title": "城市街头风格 – 老城区特辑",
            "platform": "抖音",
            "views": 28000,
            "likes": 1900,
            "comments": 156,
            "shares": 310,
            "posted": "周三 20:00",
            "pillar": "城市街头风格",
        },
        {
            "title": "预算约会穿搭准备",
            "platform": "小红书",
            "views": 11000,
            "likes": 890,
            "comments": 63,
            "shares": 92,
            "posted": "周二 19:00",
            "pillar": "预算穿搭",
        },
        {
            "title": "文化与风格 – 传承与时尚",
            "platform": "小红书",
            "views": 9400,
            "likes": 720,
            "comments": 48,
            "shares": 67,
            "posted": "周四 20:00",
            "pillar": "文化与风格",
        },
    ],
    "top_pillar": "二手改造",
    "best_time": "周一 19:00",
    "weekly_growth": [80, 120, 145, 210, 180, 240, 310],
}
